apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-component
  namespace: ingress-nginx
data:
  component: ingress-nginx
  installation: helm
