apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-component
  namespace: external-secrets
data:
  component: external-secrets
  installation: helm
