clusterConfig:
  clusterFullName: REPLACE_WITH_EKS_CLUSTER_NAME
  environment: dev
  awsRegion: REPLACE_WITH_AWS_REGION

targetRevision: main
repoURL: https://github.com/pratik-khot/gitops-repo.git

defaultSyncPolicy:
  automated:
    prune: true
    selfHeal: true

apps:
  argocd:
    enabled: true
    installer: kustomize
    path: apps/argocd/base
    project: platform
    destination:
      namespace: argocd
    argoSyncWave: "0"
    syncOptions:
      - CreateNamespace=true
  aws-load-balancer-controller:
    enabled: true
    installer: helm
    chart:
      repoURL: https://aws.github.io/eks-charts
      name: aws-load-balancer-controller
      revision: 1.11.0
    project: platform
    destination:
      namespace: kube-system
    argoSyncWave: "10"
    helmValues:
      clusterName: REPLACE_WITH_EKS_CLUSTER_NAME
      region: REPLACE_WITH_AWS_REGION
      serviceAccount:
        create: true
        name: aws-load-balancer-controller
  external-dns:
    enabled: true
    installer: helm
    chart:
      repoURL: https://kubernetes-sigs.github.io/external-dns
      name: external-dns
      revision: 1.15.0
    project: platform
    destination:
      namespace: external-dns
    argoSyncWave: "20"
    helmValues:
      provider:
        name: aws
      policy: sync
      serviceAccount:
        create: true
        name: external-dns
      domainFilters:
        - 527540700419.realhandsonlabs.net
      txtOwnerId: Z05611871GPG7UVJDOAGF
  secrets-store-csi-driver:
    enabled: true
    installer: helm
    chart:
      repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      name: secrets-store-csi-driver
      revision: 1.4.8
    project: platform
    destination:
      namespace: kube-system
    argoSyncWave: "20"
    helmValues:
      syncSecret:
        enabled: false
      enableSecretRotation: true
      rotationPollInterval: 2m
      linux:
        enabled: true
      windows:
        enabled: false
  aws-secrets-store-provider:
    enabled: true
    installer: helm
    chart:
      repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
      name: secrets-store-csi-driver-provider-aws
      revision: 0.3.11
    project: platform
    destination:
      namespace: kube-system
    argoSyncWave: "30"
    helmValues:
      serviceAccount:
        create: true
        name: secrets-store-csi-driver-provider-aws
  metrics-server:
    enabled: true
    installer: helm
    chart:
      repoURL: https://kubernetes-sigs.github.io/metrics-server
      name: metrics-server
      revision: 3.12.1
    project: platform
    destination:
      namespace: kube-system
    argoSyncWave: "30"
  argo-rollouts:
    enabled: true
    installer: helm
    chart:
      repoURL: https://argoproj.github.io/argo-helm
      name: argo-rollouts
      revision: 2.37.0
    project: platform
    destination:
      namespace: argo-rollouts
    argoSyncWave: "30"
  kube-prometheus-stack:
    enabled: true
    installer: helm
    chart:
      repoURL: https://prometheus-community.github.io/helm-charts
      name: kube-prometheus-stack
      revision: 65.8.1
    project: platform
    destination:
      namespace: monitoring
    argoSyncWave: "40"
    helmValues:
      grafana:
        enabled: true
        service:
          type: ClusterIP
      prometheus:
        prometheusSpec:
          retention: 3d
          storageSpec: {}
  vote-app:
    enabled: false
    installer: kustomize
    path: apps/vote-app/overlays/dev
    project: apps
    destination:
      namespace: vote-app-dev
    argoSyncWave: "50"
    syncOptions:
      - CreateNamespace=true
