apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-component
  namespace: monitoring
data:
  component: kube-prometheus-stack
  installation: helm
