clusterConfig:
  clusterFullName: REPLACE_WITH_PROD_EKS_CLUSTER_NAME
  environment: prod
  awsRegion: REPLACE_WITH_PROD_AWS_REGION

apps:
  demo-app:
    enabled: false
    installer: kustomize
    path: apps/demo-app/overlays/prod
    project: apps
    destination:
      namespace: demo-app-prod
    argoSyncWave: "50"
    syncOptions:
      - CreateNamespace=true
