clusterConfig:
  clusterFullName: platform-prod
  environment: dev
  awsRegion: us-east-1

apps:
  vote-app:
    enabled: true
    installer: kustomize
    path: apps/vote-app/overlays/dev
    project: apps
    destination:
      namespace: vote-app-dev
    argoSyncWave: "50"
    syncOptions:
      - CreateNamespace=true
